# Generated by Django 2.2.15 on 2020-08-06 19:25

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('sobrenome', models.CharField(blank=True, max_length=250)),
                ('telefone', models.CharField(max_length=22)),
                ('email', models.CharField(blank=True, max_length=250)),
                ('data_criacao', models.DateTimeField(default=datetime.datetime(2020, 8, 6, 19, 25, 9, 799679, tzinfo=utc))),
                ('descricao', models.TextField(blank=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contato.Categoria')),
            ],
        ),
    ]
