# Generated by Django 2.2.15 on 2020-08-06 19:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contato', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='data_criacao',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 8, 6, 19, 25, 48, 262156, tzinfo=utc)),
        ),
    ]
