# Generated by Django 2.2.15 on 2020-08-06 20:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contato', '0003_auto_20200806_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='data_criacao',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 8, 6, 20, 13, 44, 928296, tzinfo=utc)),
        ),
    ]
