# Generated by Django 2.2.15 on 2020-08-10 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contato', '0009_contato_mostrar'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='foto',
            field=models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d'),
        ),
    ]
